pretty_inspect supports Ruby 2.7
I'm trying to fix this error in 2.7:

```
FrozenError: can't modify frozen String: "false"
30
/home/runner/runner/agent/_work/kennel/kennel/vendor/bundle/ruby/2.7.0/gems/kennel-1.112.0/lib/kennel/utils.rb:153:in `gsub!'
31
/home/runner/runner/agent/_work/kennel/kennel/vendor/bundle/ruby/2.7.0/gems/kennel-1.112.0/lib/kennel/utils.rb:153:in `pretty_inspect'
32
/home/runner/runner/agent/_work/kennel/kennel/vendor/bundle/ruby/2.7.0/gems/kennel-1.112.0/lib/kennel/syncer.rb:200:in `block in print_diff'
33
```

This is due to a change on boolean `inspect`:

in 2.6:

```ruby
true.inspect.frozen?
=> false
```

in 2.7:
```
true.inspect.frozen?
=> true
```