do not allow overriding existing methods via settings since it leads to funky errors
before:
```
ArgumentError: wrong number of arguments (given 1, expected 0)
```

after:
```
rake generate
Generating ... -rake aborted!
ArgumentError: Settings :url are already used as methods
lib/kennel/models/base.rb:27:in `settings'
projects/foo.rb:69:in `<class:Dashboard>'
```